name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'
          cache: 'gradle'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Fetch Dependencies
        run: gradle -I gradle/support/fetchDependencies.gradle
      - name: Build Ghdira
        run: gradle buildGhidra
      - uses: actions/upload-artifact@v2
        with:
          name: archive
          path: build/dist/*.zip
